language: go
dist: xenial
before_install:
  - sudo apt-get install -y libopencv-dev
addons:
  apt:
    update: true
script: go test -v --race ./...
notifications:
  email:
    recipients:
      - scorpid33@gmail.com
    on_success: never
    on_failure: always
