services: docker
script:
  - docker build -t tests .
  - docker run tests go test --race -v ./...
notifications:
  email:
    recipients:
      - scorpid33@gmail.com
    on_success: never
    on_failure: always
